# Generated by Django 4.2.2 on 2025-04-15 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    ("remove_any_product", "Remove any product"),
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
