# Generated by Django 4.2.2 on 2025-04-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_is_available_product_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product/image",
                verbose_name="изображение",
            ),
        ),
    ]
